name: seven
version: '1.0-SNAPSHOT'
main: me._l4urens_.seven.Seven
api-version: '1.21'

commands:
  start:
    description: 7boom test
    usage: /<command>
  next:
    description: next

  boom:
    description: boom

